name: Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        platform: [windows-latest]
        # platform: [macos-latest, windows-latest]
        binaries: [spaceinvaders, gestrandet]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Statik
      run: go install github.com/rakyll/statik
    - name: Generate
      run: go generate ./...
    # Test breaks on Windows VM
    # https://github.com/hajimehoshi/ebiten/issues/903
    # TODO: Build only on Linux - and cross compile for all platforms?
    # - name: Test
    #   run: go test ./...
    - name: Build ${{ matrix.binaries }}
      run: go build -o ${{ matrix.binaries }}.exe ./cmd/${{ matrix.binaries }}/
    - name: Upload ${{ matrix.binaries }}
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.binaries }}-windows
        path: ${{ matrix.binaries }}.exe
